services:
  - type: web
    name: movie-match
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: COGNODB_URI
        sync: false
      - key: COGNODB_USER
        sync: false
      - key: COGNODB_PASSWORD
        sync: false
